// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsgVydSGCERItTGdAI9U5jPM8054gUmWo',
    appId: '1:118728749371:web:3680216cf314e87fe6471e',
    messagingSenderId: '118728749371',
    projectId: 'mohammed-1249b',
    authDomain: 'mohammed-1249b.firebaseapp.com',
    storageBucket: 'mohammed-1249b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7wEVxJo60rjYykffYPiacvrs6ngOXuH8',
    appId: '1:118728749371:android:87dd51e329f1bf15e6471e',
    messagingSenderId: '118728749371',
    projectId: 'mohammed-1249b',
    storageBucket: 'mohammed-1249b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD92UhEwXUhGX97fqWgoup9t2R2_pbnRLI',
    appId: '1:118728749371:ios:5ecd55e3b828f287e6471e',
    messagingSenderId: '118728749371',
    projectId: 'mohammed-1249b',
    storageBucket: 'mohammed-1249b.appspot.com',
    iosBundleId: 'com.example.gustoro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD92UhEwXUhGX97fqWgoup9t2R2_pbnRLI',
    appId: '1:118728749371:ios:5ecd55e3b828f287e6471e',
    messagingSenderId: '118728749371',
    projectId: 'mohammed-1249b',
    storageBucket: 'mohammed-1249b.appspot.com',
    iosBundleId: 'com.example.gustoro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv6J-YJzc1olFVz3XSipRHgj_J44mz55Y',
    appId: '1:118728749371:web:6bb129dfa2f55080e6471e',
    messagingSenderId: '118728749371',
    projectId: 'mohammed-1249b',
    authDomain: 'mohammed-1249b.firebaseapp.com',
    storageBucket: 'mohammed-1249b.appspot.com',
  );
}
